language: erlang # no shell language support; use least-loaded worker(s)

install: make install

env:
  - TEST_OPTS=-v
  - DEFAULT_TEST_TARGET=prove

script: make test

after_script: make uninstall

branches:
  only:
    - master
